apiVersion: v1
kind: Pod
metadata:
  name: mypod-vol
  namespace: default
spec:
  containers:
  - name: mycontainer
    image: nginx
    volumeMounts:
    - name: secret-vol
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: mysecret