apiVersion: v1
kind: Pod
metadata:
  name: mypod-env
  namespace: default
spec:
  containers:
  - name: mycontainer
    image: nginx
    env:
    - name: MY_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password