apiVersion: v1
kind: Pod
metadata:
  name: pod-aws-secret
  namespace: default
spec:
  serviceAccountName: secrets-sa
  containers:
  - name: mycontainer
    image: nginx
    volumeMounts:
    - name: secrets-store-vol
      mountPath: "/mnt/secrets-store"
      readOnly: true
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-secret-from-aws
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret-from-aws
          key: password
  volumes:
  - name: secrets-store-vol
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets-db"