apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: monitoring-lab      # Replace with your cluster name
  logs.region: us-east-1            # Replace with your AWS region